### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email":"victor@2247.com",
  "password":"mysecretkey"
}

### Get User By ID
GET http://localhost:3000/auth/1
Content-Type: application/json


### Get all users by e-mail
GET http://localhost:3000/auth?email=victor@2247.com
Content-Type: application/json