### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email":"victor@2247.com",
  "password":"mysecretkey"
}

### GET User By ID
GET http://localhost:3000/auth/2
Content-Type: application/json
